HYPERPARAMETERS: dict[str, int | float] = {
    'NUMBER_OF_EPOCHS': 16,
    'LEARNING_RATE': 0.001,
    'SEQUENCE_LENGTH': 16,
    'EMBEDDING_SIZE': 128,
    'BATCH_SIZE': 64,
    'LSTM_HIDDEN_STATE_SIZE': 128,
    'TEMPERATURE': 0.3
}